### PR TITLE
Sort globbed files for releases

### PR DESCRIPTION
**Pull request by beyarkay**
This change simply sorts the list of files after the glob has been resolved. This is useful because these files are often destined for a release, and having to scroll through hundreds of files which aren't sorted is *painful*.

# New Features
*None*

# Changes
* Sorts files before they're uploaded so that the user sees a nice, sorted list of files on the releases page.

# Bug Fixes
*None*

-----
I'm happy to convert this into an option that can be specified in the yaml if you'd prefer?

### CODE REVIEW

**Comment by Paebbels** [comment]
@umarcor I see no harm in this new behavior, so it doesn't need to be a parameter, right?

**Comment by beyarkay** [comment]
Yeah no harm at all, just wasn't sure how strict you were gonna be about the O(nlogn) time to sort the array 😄. By way of an extra example, [here's a release](https://github.com/beyarkay/eskom-calendar/releases/tag/latest) I've got. Trying to find the calendar `western-cape-stellenbosch.ics` if you're a luddite and don't know about ctrl-f is a bit tricky.

But thanks for the GH action! it's solved *so many issues* I had previously,

**Comment by beyarkay** [comment]
Is there anything preventing this from being merged?

**Review by umarcor — APPROVED** [review]
LGTM!

**Pull request merged**
