### PR TITLE
Extend Unit Tests to multiple systems (ubuntu, windows, msys2 and macos)

### PR DESCRIPTION
**Pull request by umarcor**
# New Features

* Added support for Python 3.11 pre-release versions.
* Support execution on Linux (Ubuntu), macOS and Windows.
* Support for MSYS2-MinGW64.
* Use GitHub `warning` and `notice` to tell about using Python 3.6 or 3.11.

# Changes

* Parameters: remove 3.6 from default python_version_list.
* Parameters: add option 'system_list'; UnitTesting now requires field 'system' in the matrix.
* Parameters: support system 'msys2' (MINGW64); update UnitTesting accordingly.
* Split requirements installation into a MSYS2 specific and common step.
  * Preinstall Python packages not installed on MSYS2-MinGW64 by default (wheel)
  * Preinstall packages with binary content (Coverage, lxml) via Pacman.

# Bug Fixes

*None*

---------------
**Related PRs:**
* #34
* #35
* #36

### CODE REVIEW

**Comment by umarcor** [comment]
@Paebbels both windows (powershell) and MSYS2 (MINGW64) need fixes. See https://github.com/edaa-org/pyEDAA.ProjectModel/actions/runs/1665372549. On powershell, step '☑ Run unit tests' of workflows UnitTesting fails, because the syntax is for bash. On MSYS2, some packages are installed through requirements files, which should be installed through `pacman`. We need to discuss how to handle that.

**Comment by Paebbels** [comment]
@umarcor first part is addressed in #34 and ready for review / merge.

**Comment by Paebbels** [comment]
**Questions:**
1. Should we always generate all combinations: `[3.7, ..., 3.10] × [win, mac, lin, msys] × [bash, posh, mingw32, ..., clang64]`, OR
   Should we allow Python versions per system?
2. Should we generate one JSON variable as output or one per system, so handling of Bash vs. PowerShell code gets easier?

**Comment by Paebbels** [comment]
So there are 2 pending PRs for this PR.
But all look OK.

I'll switch it to ready for review.

**Comment by Paebbels** [comment]
Argh, we need the same similar changed to coverage and other tasks:
* for powershell handling variables
* for pre-installing packages via pacman

**Comment by umarcor** [comment]
> Argh, we need the same similar changed to coverage and other tasks:

We agreed that running coverage and static type checks on linux only was good enough, so we would only support multiple systems and python versions for UnitTesting, isn't it?

**Review by Paebbels — COMMENTED** [review]
Does [line 29](https://github.com/pyTooling/Actions/pull/33/files#R29) need an update?

**Comment by Paebbels** [comment]
> We agreed that running coverage and static type checks on linux only was good enough, so we would only support multiple systems and python versions for UnitTesting, isn't it?

You're right. Just saw the code and was afraid we might have missed it. But yes, for now there is no need to run this on multiple platforms. Might come later e.g. for coverage as we might need to merge linux and windows coverage.

**Comment by umarcor** [comment]
> Does [line 29](https://github.com/pyTooling/Actions/pull/33/files#R29) need an update?

L29 of which file? The link is not jumping properly...

**Comment by umarcor** [comment]
> 1. Should we always generate all combinations: `[3.7, ..., 3.10] × [win, mac, lin, msys] × [bash, posh, mingw32, ..., clang64]`, OR
>        Should we allow Python versions per system?

For now, I think we should test all the Python version on win, mac and lin, plus a single version on MSYS2 (because it's a rolling release).

> 2. Should we generate one JSON variable as output or one per system, so handling of Bash vs. PowerShell code gets easier?

I don't think it's worth the complexity for now. Apart from having at least two variables, we would need to have multiples jobs within the reusable workflow, and that would duplicate some of the steps (checkout, update pip, upload artifact...). I feel that would not be more readable than the current approach.

**Review by Paebbels — APPROVED** [review]

**Pull request merged**
